### ISSUE TITLE
Make Peptide Importer Usable

### ISSUE THREAD

**Issue by antonneubauer** [cschlaffner/PROTzilla2#125]
### ToDos:
- [x] think about way to ensure correct intensity-type is chosen (or maybe leave up to user & log warning if against recommendations)
- [x] add step to workflow meta file
- [x] Add functionality to runner
- [x] add tests to runner

## Acceptance Criteria
- [x] New Importing-Step
- [x] Possible in Runner
