### ISSUE TITLE
#TODO log transform of 0 values in df

### ISSUE THREAD

**Issue by brokkoli71** [cschlaffner/PROTzilla2#41]
log transform of 0 is -inf. Therefore they should get dropped

search for `# TODO 41`

acceptance criteria:
- [ ] values get dropped
- [ ] message "values got dropped because..."
- [ ] dropped values in return dict
